<?php

namespace ContainerYjm9AuL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9S0t5iQService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.9S0t5iQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ad' => ['privates', '.errored..service_locator.9S0t5iQ.App\\Entity\\ClassifiedAd', NULL, 'Cannot autowire service ".service_locator.9S0t5iQ": it needs an instance of "App\\Entity\\ClassifiedAd" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'ad' => 'App\\Entity\\ClassifiedAd',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.9S0t5iQ'])) {
            return $container->privates['.service_locator.9S0t5iQ'];
        }

        return $container->privates['.service_locator.9S0t5iQ'] = $instance;
    }
}
