<?php

namespace ContainerYjm9AuL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArchiveImageService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.b2vch_B.App\Entity\ArchiveImage' shared service.
     *
     * @return \App\Entity\ArchiveImage
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.b2vch_B": it needs an instance of "App\\Entity\\ArchiveImage" but this type has been excluded in "config/services.yaml".');
    }
}
