<?php

namespace ContainerYjm9AuL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleAttachmentRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ArticleAttachmentRepository' shared autowired service.
     *
     * @return \App\Repository\ArticleAttachmentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ArticleAttachmentRepository'] = new \App\Repository\ArticleAttachmentRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
