<?php

namespace ContainerYjm9AuL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttachmentControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AttachmentController' shared autowired service.
     *
     * @return \App\Controller\AttachmentController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AttachmentController'] = $instance = new \App\Controller\AttachmentController(($container->services['vich_uploader.download_handler'] ?? $container->load('getVichUploader_DownloadHandlerService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\AttachmentController', $container));

        return $instance;
    }
}
