<?php

namespace ContainerYjm9AuL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassifiedAdServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\ClassifiedAdService' shared autowired service.
     *
     * @return \App\Service\ClassifiedAdService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\ClassifiedAdService'] = new \App\Service\ClassifiedAdService(($container->privates['App\\Repository\\ClassifiedAdRepository'] ?? $container->load('getClassifiedAdRepositoryService')));
    }
}
