<?php

namespace ContainerYjm9AuL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassifiedAdCrudControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\ClassifiedAdCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\ClassifiedAdCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \App\Controller\Admin\ClassifiedAdCrudController();

        if (isset($container->services['App\\Controller\\Admin\\ClassifiedAdCrudController'])) {
            return $container->services['App\\Controller\\Admin\\ClassifiedAdCrudController'];
        }

        $container->services['App\\Controller\\Admin\\ClassifiedAdCrudController'] = $instance;

        $instance->setContainer(($container->privates['.service_locator.OkS5_e6'] ?? $container->load('get_ServiceLocator_OkS5E6Service'))->withContext('App\\Controller\\Admin\\ClassifiedAdCrudController', $container));

        return $instance;
    }
}
