<?php

namespace ContainerYjm9AuL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHelloAssoControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Webhook\HelloAssoController' shared autowired service.
     *
     * @return \App\Controller\Webhook\HelloAssoController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Controller\\Webhook\\HelloAssoController'] = new \App\Controller\Webhook\HelloAssoController(new \App\Service\HelloAsso\HelloAssoWebhookHandler(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'))));
    }
}
