<?php

namespace ContainerYjm9AuL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMembershipApplicationCrudControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\MembershipApplicationCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\MembershipApplicationCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['App\\Controller\\Admin\\MembershipApplicationCrudController'])) {
            return $container->services['App\\Controller\\Admin\\MembershipApplicationCrudController'];
        }

        $instance = new \App\Controller\Admin\MembershipApplicationCrudController(new \App\Service\MembershipApprover($a), (isset($container->factories['service_container']['EasyCorp\\Bundle\\EasyAdminBundle\\Router\\AdminUrlGenerator']) ? $container->factories['service_container']['EasyCorp\\Bundle\\EasyAdminBundle\\Router\\AdminUrlGenerator']($container) : self::getAdminUrlGeneratorService($container)));

        if (isset($container->services['App\\Controller\\Admin\\MembershipApplicationCrudController'])) {
            return $container->services['App\\Controller\\Admin\\MembershipApplicationCrudController'];
        }

        $container->services['App\\Controller\\Admin\\MembershipApplicationCrudController'] = $instance;

        $instance->setContainer(($container->privates['.service_locator.OkS5_e6'] ?? $container->load('get_ServiceLocator_OkS5E6Service'))->withContext('App\\Controller\\Admin\\MembershipApplicationCrudController', $container));

        return $instance;
    }
}
