<?php

namespace ContainerYjm9AuL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMyEventControllerindexService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Zvid8lw.App\Controller\Account\MyEventController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zvid8lw.App\\Controller\\Account\\MyEventController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\EventRepository',
        ]))->withContext('App\\Controller\\Account\\MyEventController::index()', $container);
    }
}
