<?php

namespace ContainerYjm9AuL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpenMeteoServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\OpenMeteoService' shared autowired service.
     *
     * @return \App\Service\OpenMeteoService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\OpenMeteoService'] = new \App\Service\OpenMeteoService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->services['cache.app'] ?? $container->load('getCache_AppService')));
    }
}
