<?php

namespace ContainerYjm9AuL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhotoTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\PhotoType' shared autowired service.
     *
     * @return \App\Form\PhotoType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PhotoType'] = new \App\Form\PhotoType();
    }
}
