<?php

namespace ContainerYjm9AuL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhotoControlleruploadService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.73Za615.App\Controller\PhotoController::upload()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'em' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\PhotoController::upload()', $container);

        if (isset($container->privates['.service_locator.73Za615.App\\Controller\\PhotoController::upload()'])) {
            return $container->privates['.service_locator.73Za615.App\\Controller\\PhotoController::upload()'];
        }

        return $container->privates['.service_locator.73Za615.App\\Controller\\PhotoController::upload()'] = $instance;
    }
}
