<?php

namespace ContainerYjm9AuL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhotoThumbnailSubscriberService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\EventSubscriber\PhotoThumbnailSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\PhotoThumbnailSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['liip_imagine.cache.manager'] ?? $container->load('getLiipImagine_Cache_ManagerService'));

        if (isset($container->privates['App\\EventSubscriber\\PhotoThumbnailSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\PhotoThumbnailSubscriber'];
        }

        $instance = new \App\EventSubscriber\PhotoThumbnailSubscriber($a);

        if (isset($container->privates['App\\EventSubscriber\\PhotoThumbnailSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\PhotoThumbnailSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\PhotoThumbnailSubscriber'] = $instance;
    }
}
