<?php

namespace ContainerYjm9AuL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhotoControllerindexService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.La5l3E5.App\Controller\PhotoController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'photoRepository' => ['privates', 'App\\Repository\\PhotoRepository', 'getPhotoRepositoryService', true],
            'albumRepository' => ['privates', 'App\\Repository\\AlbumRepository', 'getAlbumRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'photoRepository' => 'App\\Repository\\PhotoRepository',
            'albumRepository' => 'App\\Repository\\AlbumRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\PhotoController::index()', $container);

        if (isset($container->privates['.service_locator.La5l3E5.App\\Controller\\PhotoController::index()'])) {
            return $container->privates['.service_locator.La5l3E5.App\\Controller\\PhotoController::index()'];
        }

        return $container->privates['.service_locator.La5l3E5.App\\Controller\\PhotoController::index()'] = $instance;
    }
}
