<?php

namespace ContainerYjm9AuL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserCrudControllerapproveUserService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.2iqFKH_.App\Controller\Admin\UserCrudController::approveUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'context' => ['privates', '.errored..service_locator.2iqFKH_.EasyCorp\\Bundle\\EasyAdminBundle\\Context\\AdminContext', NULL, 'Cannot autowire service ".service_locator.2iqFKH_": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Context\\AdminContext" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'adminUrlGenerator' => [false, 'EasyCorp\\Bundle\\EasyAdminBundle\\Router\\AdminUrlGenerator', 'getAdminUrlGeneratorService', false],
        ], [
            'context' => 'EasyCorp\\Bundle\\EasyAdminBundle\\Context\\AdminContext',
            'em' => '?',
            'adminUrlGenerator' => 'EasyCorp\\Bundle\\EasyAdminBundle\\Router\\AdminUrlGenerator',
        ]))->withContext('App\\Controller\\Admin\\UserCrudController::approveUser()', $container);

        if (isset($container->privates['.service_locator.2iqFKH_.App\\Controller\\Admin\\UserCrudController::approveUser()'])) {
            return $container->privates['.service_locator.2iqFKH_.App\\Controller\\Admin\\UserCrudController::approveUser()'];
        }

        return $container->privates['.service_locator.2iqFKH_.App\\Controller\\Admin\\UserCrudController::approveUser()'] = $instance;
    }
}
