<?php

namespace ContainerYjm9AuL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserCrudControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\UserCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\UserCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService'));

        if (isset($container->services['App\\Controller\\Admin\\UserCrudController'])) {
            return $container->services['App\\Controller\\Admin\\UserCrudController'];
        }
        $b = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));

        if (isset($container->services['App\\Controller\\Admin\\UserCrudController'])) {
            return $container->services['App\\Controller\\Admin\\UserCrudController'];
        }
        $c = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->services['App\\Controller\\Admin\\UserCrudController'])) {
            return $container->services['App\\Controller\\Admin\\UserCrudController'];
        }

        $instance = new \App\Controller\Admin\UserCrudController(new \Symfony\Component\Mailer\Mailer($a, $b, $c));

        if (isset($container->services['App\\Controller\\Admin\\UserCrudController'])) {
            return $container->services['App\\Controller\\Admin\\UserCrudController'];
        }

        $container->services['App\\Controller\\Admin\\UserCrudController'] = $instance;

        $instance->setContainer(($container->privates['.service_locator.OkS5_e6'] ?? $container->load('get_ServiceLocator_OkS5E6Service'))->withContext('App\\Controller\\Admin\\UserCrudController', $container));

        return $instance;
    }
}
