<?php

namespace ContainerYjm9AuL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUxMap_TwigRuntimeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'ux_map.twig_runtime' shared service.
     *
     * @return \Symfony\UX\Map\Twig\MapRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['ux_map.twig_runtime'] = new \Symfony\UX\Map\Twig\MapRuntime((new \Symfony\UX\Map\Renderer\Renderer(new RewindableGenerator(fn () => new \EmptyIterator(), 0)))->fromStrings(['default' => $container->getEnv('resolve:default::UX_MAP_DSN')]));
    }
}
