<?php

namespace ContainerYjm9AuL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVichUploader_Listener_Clean_PhotosService extends App_KernelProdContainer
{
    /*
     * Gets the private 'vich_uploader.listener.clean.photos' shared service.
     *
     * @return \Vich\UploaderBundle\EventListener\Doctrine\CleanListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['vich_uploader.upload_handler'] ?? $container->load('getVichUploader_UploadHandlerService'));

        if (isset($container->privates['vich_uploader.listener.clean.photos'])) {
            return $container->privates['vich_uploader.listener.clean.photos'];
        }

        $instance = new \Vich\UploaderBundle\EventListener\Doctrine\CleanListener('photos', ($container->privates['vich_uploader.adapter.orm'] ??= new \Vich\UploaderBundle\Adapter\ORM\DoctrineORMAdapter()), ($container->privates['vich_uploader.metadata_reader'] ?? $container->load('getVichUploader_MetadataReaderService')), $a);

        if (isset($container->privates['vich_uploader.listener.clean.photos'])) {
            return $container->privates['vich_uploader.listener.clean.photos'];
        }

        return $container->privates['vich_uploader.listener.clean.photos'] = $instance;
    }
}
