vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        photos:
            uri_prefix: /uploads/photos
            upload_destination: '%kernel.project_dir%/public/uploads/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        board_member_photos:
            uri_prefix: /uploads/board_members
            upload_destination: '%kernel.project_dir%/public/uploads/board_members'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

    metadata:
        type: attribute
    mappings:
        classified_ad_photo:
            uri_prefix: /uploads/classifieds
            upload_destination: '%kernel.project_dir%/public/uploads/classifieds'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

