<?php

namespace ContainerSE10xGr;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_H1axUP7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.H1axUP7' shared service.
     *
     * @return \App\Controller\EventRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\AccountController::delete()": the $eventRepo argument is type-hinted with the non-existent class or interface: "App\\Controller\\EventRepository". Did you forget to add a use statement?');
    }
}
