<?php

namespace ContainerSE10xGr;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccountControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.59hHM6R.App\Controller\AccountController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.59hHM6R.App\\Controller\\AccountController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'eventRepo' => ['privates', '.errored.H1axUP7', NULL, 'Cannot determine controller argument for "App\\Controller\\AccountController::delete()": the $eventRepo argument is type-hinted with the non-existent class or interface: "App\\Controller\\EventRepository". Did you forget to add a use statement?'],
        ], [
            'em' => '?',
            'eventRepo' => '?',
        ]))->withContext('App\\Controller\\AccountController::delete()', $container);
    }
}
