<?php

namespace ContainerSE10xGr;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccountAdControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9S0t5iQ.App\Controller\Account\AccountAdController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.9S0t5iQ'] ?? $container->load('get_ServiceLocator_9S0t5iQService'));

        if (isset($container->privates['.service_locator.9S0t5iQ.App\\Controller\\Account\\AccountAdController::edit()'])) {
            return $container->privates['.service_locator.9S0t5iQ.App\\Controller\\Account\\AccountAdController::edit()'];
        }

        return $container->privates['.service_locator.9S0t5iQ.App\\Controller\\Account\\AccountAdController::edit()'] = $a->withContext('App\\Controller\\Account\\AccountAdController::edit()', $container);
    }
}
