<?php

namespace ContainerSE10xGr;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleAttachmentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VYwb7sT.App\Entity\ArticleAttachment' shared service.
     *
     * @return \App\Entity\ArticleAttachment
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.VYwb7sT": it needs an instance of "App\\Entity\\ArticleAttachment" but this type has been excluded in "config/services.yaml".');
    }
}
