<?php

namespace ContainerSE10xGr;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassifiedAdServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ClassifiedAdService' shared autowired service.
     *
     * @return \App\Service\ClassifiedAdService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ClassifiedAdService.php';

        return $container->privates['App\\Service\\ClassifiedAdService'] = new \App\Service\ClassifiedAdService(($container->privates['App\\Repository\\ClassifiedAdRepository'] ?? $container->load('getClassifiedAdRepositoryService')));
    }
}
