<?php

namespace ContainerSE10xGr;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHeaderControllersiteHeaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.im72byE.App\Controller\HeaderController::siteHeader()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.im72byE.App\\Controller\\HeaderController::siteHeader()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'om' => ['privates', 'App\\Service\\OpenMeteoService', 'getOpenMeteoServiceService', true],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', true],
        ], [
            'om' => 'App\\Service\\OpenMeteoService',
            'logger' => '?',
        ]))->withContext('App\\Controller\\HeaderController::siteHeader()', $container);
    }
}
