<?php

namespace ContainerSE10xGr;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHelloAssoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Webhook\HelloAssoController' shared autowired service.
     *
     * @return \App\Controller\Webhook\HelloAssoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Webhook'.\DIRECTORY_SEPARATOR.'HelloAssoController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'HelloAsso'.\DIRECTORY_SEPARATOR.'HelloAssoWebhookHandler.php';

        return $container->services['App\\Controller\\Webhook\\HelloAssoController'] = new \App\Controller\Webhook\HelloAssoController(new \App\Service\HelloAsso\HelloAssoWebhookHandler(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'))));
    }
}
