<?php

namespace ContainerSE10xGr;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpenMeteoServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\OpenMeteoService' shared autowired service.
     *
     * @return \App\Service\OpenMeteoService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'OpenMeteoService.php';

        return $container->privates['App\\Service\\OpenMeteoService'] = new \App\Service\OpenMeteoService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->services['cache.app'] ?? self::getCache_AppService($container)));
    }
}
