<?php

namespace ContainerRzmuz2U;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleVoterService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Security\Voter\ArticleVoter' shared autowired service.
     *
     * @return \App\Security\Voter\ArticleVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\Voter\\ArticleVoter'] = new \App\Security\Voter\ArticleVoter(($container->privates['App\\Repository\\MembershipRepository'] ?? $container->load('getMembershipRepositoryService')));
    }
}
