<?php

namespace ContainerRzmuz2U;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlbumTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\AlbumType' shared autowired service.
     *
     * @return \App\Form\AlbumType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AlbumType'] = new \App\Form\AlbumType();
    }
}
