<?php

namespace ContainerRzmuz2U;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBoardMemberControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\BoardMemberController' shared autowired service.
     *
     * @return \App\Controller\BoardMemberController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\BoardMemberController'] = $instance = new \App\Controller\BoardMemberController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\BoardMemberController', $container));

        return $instance;
    }
}
