<?php

namespace ContainerRzmuz2U;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBoardMemberControllerorganigramService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.Kq27LHM.App\Controller\BoardMemberController::organigram()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Kq27LHM.App\\Controller\\BoardMemberController::organigram()'] = ($container->privates['.service_locator.Kq27LHM'] ?? $container->load('get_ServiceLocator_Kq27LHMService'))->withContext('App\\Controller\\BoardMemberController::organigram()', $container);
    }
}
