<?php

namespace ContainerRzmuz2U;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBoardMemberCrudControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\Admin\BoardMemberCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\BoardMemberCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\BoardMemberCrudController'] = $instance = new \App\Controller\Admin\BoardMemberCrudController();

        $instance->setContainer(($container->privates['.service_locator.5PWTx9U'] ?? $container->load('get_ServiceLocator_5PWTx9UService'))->withContext('App\\Controller\\Admin\\BoardMemberCrudController', $container));

        return $instance;
    }
}
