<?php

namespace ContainerRzmuz2U;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassifiedAdTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\ClassifiedAdType' shared autowired service.
     *
     * @return \App\Form\ClassifiedAdType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ClassifiedAdType'] = new \App\Form\ClassifiedAdType();
    }
}
