<?php

namespace ContainerRzmuz2U;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassifiedAdControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\ClassifiedAdController' shared autowired service.
     *
     * @return \App\Controller\ClassifiedAdController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ClassifiedAdController'] = $instance = new \App\Controller\ClassifiedAdController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\ClassifiedAdController', $container));

        return $instance;
    }
}
