<?php

namespace ContainerRzmuz2U;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassifiedAd2Service extends App_KernelDevContainer
{
    /*
     * Gets the private '.errored..service_locator.Tfsgm_V.App\Entity\ClassifiedAd' shared service.
     *
     * @return \App\Entity\ClassifiedAd
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Tfsgm_V": it needs an instance of "App\\Entity\\ClassifiedAd" but this type has been excluded in "config/services.yaml".');
    }
}
