<?php

namespace ContainerRzmuz2U;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHeaderControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\HeaderController' shared autowired service.
     *
     * @return \App\Controller\HeaderController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\HeaderController'] = $instance = new \App\Controller\HeaderController(47.52, -2.3, 47.45, -2.5, 'Europe/Paris');

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\HeaderController', $container));

        return $instance;
    }
}
