<?php

namespace ContainerRzmuz2U;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMembershipRepositoryService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Repository\MembershipRepository' shared autowired service.
     *
     * @return \App\Repository\MembershipRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\MembershipRepository'] = new \App\Repository\MembershipRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
