<?php

namespace ContainerRzmuz2U;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMyEventControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\Account\MyEventController' shared autowired service.
     *
     * @return \App\Controller\Account\MyEventController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Account\\MyEventController'] = $instance = new \App\Controller\Account\MyEventController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Account\\MyEventController', $container));

        return $instance;
    }
}
