<?php

namespace ContainerRzmuz2U;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpenMeteoServiceService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Service\OpenMeteoService' shared autowired service.
     *
     * @return \App\Service\OpenMeteoService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\OpenMeteoService'] = new \App\Service\OpenMeteoService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->services['cache.app'] ?? $container->load('getCache_AppService')));
    }
}
