<?php

namespace ContainerRzmuz2U;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhotoCrudControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\Admin\PhotoCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\PhotoCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\PhotoCrudController'] = $instance = new \App\Controller\Admin\PhotoCrudController();

        $instance->setContainer(($container->privates['.service_locator.5PWTx9U'] ?? $container->load('get_ServiceLocator_5PWTx9UService'))->withContext('App\\Controller\\Admin\\PhotoCrudController', $container));

        return $instance;
    }
}
