<?php

namespace ContainerRzmuz2U;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhotoThumbnailSubscriberService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\EventSubscriber\PhotoThumbnailSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\PhotoThumbnailSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['liip_imagine.cache.manager'] ?? self::getLiipImagine_Cache_ManagerService($container));

        if (isset($container->privates['App\\EventSubscriber\\PhotoThumbnailSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\PhotoThumbnailSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\PhotoThumbnailSubscriber'] = new \App\EventSubscriber\PhotoThumbnailSubscriber($a);
    }
}
