<?php

namespace ContainerRzmuz2U;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhotoControllerindexService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.vTMxsrT.App\Controller\PhotoController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vTMxsrT.App\\Controller\\PhotoController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'photoRepository' => ['privates', 'App\\Repository\\PhotoRepository', 'getPhotoRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'photoRepository' => 'App\\Repository\\PhotoRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\PhotoController::index()', $container);
    }
}
