<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYjm9AuL\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYjm9AuL/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerYjm9AuL.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerYjm9AuL\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerYjm9AuL\App_KernelProdContainer([
    'container.build_hash' => 'Yjm9AuL',
    'container.build_id' => '19e92ad7',
    'container.build_time' => 1768554766,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYjm9AuL');
