<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'articles' => [parent::class, 'articles', null, 16],
        "\0".parent::class."\0".'avatar' => [parent::class, 'avatar', null, 16],
        "\0".parent::class."\0".'classifiedAds' => [parent::class, 'classifiedAds', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'eventsCreated' => [parent::class, 'eventsCreated', null, 16],
        "\0".parent::class."\0".'firstName' => [parent::class, 'firstName', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isApproved' => [parent::class, 'isApproved', null, 16],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null, 16],
        "\0".parent::class."\0".'memberships' => [parent::class, 'memberships', null, 16],
        "\0".parent::class."\0".'newsletterOptIn' => [parent::class, 'newsletterOptIn', null, 16],
        "\0".parent::class."\0".'outingRequests' => [parent::class, 'outingRequests', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null, 16],
        "\0".parent::class."\0".'photos' => [parent::class, 'photos', null, 16],
        "\0".parent::class."\0".'processedApplications' => [parent::class, 'processedApplications', null, 16],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'articles' => [parent::class, 'articles', null, 16],
        'avatar' => [parent::class, 'avatar', null, 16],
        'classifiedAds' => [parent::class, 'classifiedAds', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'eventsCreated' => [parent::class, 'eventsCreated', null, 16],
        'firstName' => [parent::class, 'firstName', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isApproved' => [parent::class, 'isApproved', null, 16],
        'lastName' => [parent::class, 'lastName', null, 16],
        'memberships' => [parent::class, 'memberships', null, 16],
        'newsletterOptIn' => [parent::class, 'newsletterOptIn', null, 16],
        'outingRequests' => [parent::class, 'outingRequests', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'phone' => [parent::class, 'phone', null, 16],
        'photos' => [parent::class, 'photos', null, 16],
        'processedApplications' => [parent::class, 'processedApplications', null, 16],
        'roles' => [parent::class, 'roles', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
