<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__ClassifiedAd__CLASSMETADATA__' => 0,
'App__Entity__Event__CLASSMETADATA__' => 1,
'App__Entity__ArticleAttachment__CLASSMETADATA__' => 2,
'App__Entity__Photo__CLASSMETADATA__' => 3,
'App__Entity__Album__CLASSMETADATA__' => 4,
'App__Entity__Article__CLASSMETADATA__' => 5,
'App__Entity__BoardMember__CLASSMETADATA__' => 6,
'App__Entity__Membership__CLASSMETADATA__' => 7,
'App__Entity__MembershipApplication__CLASSMETADATA__' => 8,
'App__Entity__OutingRequest__CLASSMETADATA__' => 9,
'App__Entity__Page__CLASSMETADATA__' => 10,
'App__Entity__PartnerLink__CLASSMETADATA__' => 11,
'App__Entity__User__CLASSMETADATA__' => 12,
'Vich__UploaderBundle__Entity__File__CLASSMETADATA__' => 13,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\ClassifiedAd',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ClassifiedAdRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'title' => $o[2],
                    'description' => $o[3],
                    'price' => $o[4],
                    'condition' => $o[5],
                    'location' => $o[6],
                    'status' => $o[7],
                    'publishedAt' => $o[8],
                    'createdAt' => $o[9],
                    'updatedAt' => $o[10],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'description' => 'description',
                    'price' => 'price',
                    'item_condition' => 'condition',
                    'location' => 'location',
                    'status' => 'status',
                    'published_at' => 'publishedAt',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'description' => 'description',
                    'price' => 'price',
                    'condition' => 'item_condition',
                    'location' => 'location',
                    'status' => 'status',
                    'publishedAt' => 'published_at',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'classified_ads',
                ],
            ],
            'lifecycleCallbacks' => [
                [
                    'prePersist' => [
                        'onPrePersist',
                    ],
                    'preUpdate' => [
                        'onPreUpdate',
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'owner' => $o[11],
                    'photos' => $o[13],
                ],
            ],
            'idGenerator' => [
                $o[14],
            ],
            'name' => [
                'App\\Entity\\ClassifiedAd',
                12 => 'owner_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'text',
                'decimal',
                'string',
                'string',
                'string',
                'datetime_immutable',
                'datetime_immutable',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'title',
                'description',
                'price',
                'condition',
                'location',
                'status',
                'publishedAt',
                'createdAt',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'title',
                'description',
                'price',
                'item_condition',
                'location',
                'status',
                'published_at',
                'created_at',
                'updated_at',
            ],
            'length' => [
                2 => 180,
                5 => 80,
                160,
            ],
            'nullable' => [
                4 => true,
                true,
                true,
                8 => true,
                12 => false,
            ],
            'precision' => [
                4 => 10,
            ],
            'scale' => [
                4 => 2,
            ],
            'enumType' => [
                7 => 'App\\Enum\\AdStatus',
            ],
            'fetch' => [
                11 => 2,
                13 => 2,
            ],
            'sourceEntity' => [
                11 => 'App\\Entity\\ClassifiedAd',
                13 => 'App\\Entity\\ClassifiedAd',
            ],
            'inversedBy' => [
                11 => 'classifiedAds',
            ],
            'sourceToTargetKeyColumns' => [
                11 => [
                    'owner_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                11 => [
                    'id' => 'owner_id',
                ],
            ],
            'joinColumns' => [
                11 => [
                    $o[12],
                ],
            ],
            'joinColumnFieldNames' => [
                11 => [
                    'owner_id' => 'owner_id',
                ],
            ],
            'deferrable' => [
                12 => false,
            ],
            'unique' => [
                12 => false,
            ],
            'referencedColumnName' => [
                12 => 'id',
            ],
            'cascade' => [
                13 => [
                    'persist',
                ],
            ],
            'mappedBy' => [
                13 => 'classifiedAd',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                11 => 'owner',
                13 => 'photos',
            ],
            'targetEntity' => [
                11 => 'App\\Entity\\User',
                13 => 'App\\Entity\\Photo',
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Event',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\EventRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'title' => $o[2],
                    'slug' => $o[3],
                    'description' => $o[4],
                    'type' => $o[5],
                    'registrationOpen' => $o[6],
                    'isMembersOnly' => $o[7],
                    'startAt' => $o[8],
                    'endAt' => $o[9],
                    'locationName' => $o[10],
                    'lat' => $o[11],
                    'lng' => $o[12],
                    'maxParticipants' => $o[13],
                    'status' => $o[14],
                    'createdAt' => $o[15],
                    'updatedAt' => $o[16],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'slug' => 'slug',
                    'description' => 'description',
                    'type' => 'type',
                    'registration_open' => 'registrationOpen',
                    'is_members_only' => 'isMembersOnly',
                    'start_at' => 'startAt',
                    'end_at' => 'endAt',
                    'location_name' => 'locationName',
                    'lat' => 'lat',
                    'lng' => 'lng',
                    'max_participants' => 'maxParticipants',
                    'status' => 'status',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'slug' => 'slug',
                    'description' => 'description',
                    'type' => 'type',
                    'registrationOpen' => 'registration_open',
                    'isMembersOnly' => 'is_members_only',
                    'startAt' => 'start_at',
                    'endAt' => 'end_at',
                    'locationName' => 'location_name',
                    'lat' => 'lat',
                    'lng' => 'lng',
                    'maxParticipants' => 'max_participants',
                    'status' => 'status',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'event',
                ],
            ],
            'lifecycleCallbacks' => [
                [
                    'prePersist' => [
                        'onPrePersist',
                    ],
                    'preUpdate' => [
                        'onPreUpdate',
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'createdBy' => $o[17],
                    'outingRequests' => $o[19],
                ],
            ],
            'idGenerator' => [
                $o[20],
            ],
            'name' => [
                'App\\Entity\\Event',
                18 => 'created_by_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'text',
                'string',
                'boolean',
                'boolean',
                'datetime_immutable',
                'datetime_immutable',
                'string',
                'decimal',
                'decimal',
                'smallint',
                'string',
                'datetime_immutable',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'title',
                'slug',
                'description',
                'type',
                'registrationOpen',
                'isMembersOnly',
                'startAt',
                'endAt',
                'locationName',
                'lat',
                'lng',
                'maxParticipants',
                'status',
                'createdAt',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'title',
                'slug',
                'description',
                'type',
                'registration_open',
                'is_members_only',
                'start_at',
                'end_at',
                'location_name',
                'lat',
                'lng',
                'max_participants',
                'status',
                'created_at',
                'updated_at',
            ],
            'length' => [
                2 => 255,
                255,
                5 => 32,
                10 => 255,
                14 => 16,
            ],
            'unique' => [
                3 => true,
                18 => false,
            ],
            'options' => [
                6 => [
                    'default' => false,
                ],
                [
                    'default' => false,
                ],
            ],
            'nullable' => [
                9 => true,
                true,
                true,
                true,
                true,
                18 => false,
            ],
            'precision' => [
                11 => 9,
                9,
            ],
            'scale' => [
                11 => 6,
                6,
            ],
            'fetch' => [
                17 => 2,
                19 => 2,
            ],
            'sourceEntity' => [
                17 => 'App\\Entity\\Event',
                19 => 'App\\Entity\\Event',
            ],
            'inversedBy' => [
                17 => 'eventsCreated',
            ],
            'sourceToTargetKeyColumns' => [
                17 => [
                    'created_by_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                17 => [
                    'id' => 'created_by_id',
                ],
            ],
            'joinColumns' => [
                17 => [
                    $o[18],
                ],
            ],
            'joinColumnFieldNames' => [
                17 => [
                    'created_by_id' => 'created_by_id',
                ],
            ],
            'deferrable' => [
                18 => false,
            ],
            'referencedColumnName' => [
                18 => 'id',
            ],
            'cascade' => [
                19 => [
                    'remove',
                ],
            ],
            'orphanRemoval' => [
                19 => true,
            ],
            'mappedBy' => [
                19 => 'event',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                17 => 'createdBy',
                19 => 'outingRequests',
            ],
            'targetEntity' => [
                17 => 'App\\Entity\\User',
                19 => 'App\\Entity\\OutingRequest',
            ],
        ],
    ],
    $o[0],
    []
); } },
2 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\ArticleAttachment',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ArticleAttachmentRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'title' => $o[2],
                    'fileName' => $o[3],
                    'originalName' => $o[4],
                    'mimeType' => $o[5],
                    'size' => $o[6],
                    'position' => $o[7],
                    'createdAt' => $o[8],
                    'updatedAt' => $o[9],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'file_name' => 'fileName',
                    'original_name' => 'originalName',
                    'mime_type' => 'mimeType',
                    'size' => 'size',
                    'position' => 'position',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'fileName' => 'file_name',
                    'originalName' => 'original_name',
                    'mimeType' => 'mime_type',
                    'size' => 'size',
                    'position' => 'position',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'article_attachment',
                ],
            ],
            'lifecycleCallbacks' => [
                [
                    'prePersist' => [
                        'onPrePersist',
                    ],
                    'preUpdate' => [
                        'onPreUpdate',
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'article' => $o[10],
                ],
            ],
            'idGenerator' => [
                $o[12],
            ],
            'name' => [
                'App\\Entity\\ArticleAttachment',
                11 => 'article_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'string',
                'integer',
                'smallint',
                'datetime_immutable',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'title',
                'fileName',
                'originalName',
                'mimeType',
                'size',
                'position',
                'createdAt',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'title',
                'file_name',
                'original_name',
                'mime_type',
                'size',
                'position',
                'created_at',
                'updated_at',
            ],
            'length' => [
                2 => 255,
                255,
                255,
                255,
            ],
            'nullable' => [
                2 => true,
                true,
                true,
                true,
                true,
                11 => false,
            ],
            'options' => [
                7 => [
                    'default' => 0,
                ],
            ],
            'fetch' => [
                10 => 2,
            ],
            'sourceEntity' => [
                10 => 'App\\Entity\\ArticleAttachment',
            ],
            'inversedBy' => [
                10 => 'attachments',
            ],
            'sourceToTargetKeyColumns' => [
                10 => [
                    'article_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                10 => [
                    'id' => 'article_id',
                ],
            ],
            'joinColumns' => [
                10 => [
                    $o[11],
                ],
            ],
            'joinColumnFieldNames' => [
                10 => [
                    'article_id' => 'article_id',
                ],
            ],
            'deferrable' => [
                11 => false,
            ],
            'unique' => [
                11 => false,
            ],
            'referencedColumnName' => [
                11 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                10 => 'article',
            ],
            'targetEntity' => [
                10 => 'App\\Entity\\Article',
            ],
        ],
    ],
    $o[0],
    []
); } },
3 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Photo',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\PhotoRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'fileName' => $o[2],
                    'title' => $o[3],
                    'description' => $o[4],
                    'visibility' => $o[5],
                    'takenAt' => $o[6],
                    'uploadedAt' => $o[7],
                    'updatedAt' => $o[8],
                    'deletedAt' => $o[9],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'file_name' => 'fileName',
                    'title' => 'title',
                    'description' => 'description',
                    'visibility' => 'visibility',
                    'taken_at' => 'takenAt',
                    'uploaded_at' => 'uploadedAt',
                    'updated_at' => 'updatedAt',
                    'deleted_at' => 'deletedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'fileName' => 'file_name',
                    'title' => 'title',
                    'description' => 'description',
                    'visibility' => 'visibility',
                    'takenAt' => 'taken_at',
                    'uploadedAt' => 'uploaded_at',
                    'updatedAt' => 'updated_at',
                    'deletedAt' => 'deleted_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'photos',
                ],
            ],
            'lifecycleCallbacks' => [
                [
                    'preUpdate' => [
                        'touch',
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'owner' => $o[10],
                    'album' => $o[12],
                    'classifiedAd' => $o[14],
                ],
            ],
            'idGenerator' => [
                $o[16],
            ],
            'name' => [
                'App\\Entity\\Photo',
                11 => 'owner_id',
                13 => 'album_id',
                15 => 'classified_ad_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'text',
                'string',
                'datetime_immutable',
                'datetime_immutable',
                'datetime_immutable',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'fileName',
                'title',
                'description',
                'visibility',
                'takenAt',
                'uploadedAt',
                'updatedAt',
                'deletedAt',
            ],
            'columnName' => [
                1 => 'id',
                'file_name',
                'title',
                'description',
                'visibility',
                'taken_at',
                'uploaded_at',
                'updated_at',
                'deleted_at',
            ],
            'length' => [
                2 => 255,
                180,
            ],
            'nullable' => [
                2 => true,
                true,
                true,
                6 => true,
                9 => true,
                11 => true,
                13 => true,
                15 => true,
            ],
            'enumType' => [
                5 => 'App\\Enum\\MediaVisibility',
            ],
            'fetch' => [
                10 => 2,
                12 => 2,
                14 => 2,
            ],
            'sourceEntity' => [
                10 => 'App\\Entity\\Photo',
                12 => 'App\\Entity\\Photo',
                14 => 'App\\Entity\\Photo',
            ],
            'inversedBy' => [
                10 => 'photos',
                12 => 'photos',
                14 => 'photos',
            ],
            'sourceToTargetKeyColumns' => [
                10 => [
                    'owner_id' => 'id',
                ],
                12 => [
                    'album_id' => 'id',
                ],
                14 => [
                    'classified_ad_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                10 => [
                    'id' => 'owner_id',
                ],
                12 => [
                    'id' => 'album_id',
                ],
                14 => [
                    'id' => 'classified_ad_id',
                ],
            ],
            'joinColumns' => [
                10 => [
                    $o[11],
                ],
                12 => [
                    $o[13],
                ],
                14 => [
                    $o[15],
                ],
            ],
            'joinColumnFieldNames' => [
                10 => [
                    'owner_id' => 'owner_id',
                ],
                12 => [
                    'album_id' => 'album_id',
                ],
                14 => [
                    'classified_ad_id' => 'classified_ad_id',
                ],
            ],
            'deferrable' => [
                11 => false,
                13 => false,
                15 => false,
            ],
            'unique' => [
                11 => false,
                13 => false,
                15 => false,
            ],
            'onDelete' => [
                11 => 'SET NULL',
                13 => 'SET NULL',
                15 => 'SET NULL',
            ],
            'referencedColumnName' => [
                11 => 'id',
                13 => 'id',
                15 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                10 => 'owner',
                12 => 'album',
                14 => 'classifiedAd',
            ],
            'targetEntity' => [
                10 => 'App\\Entity\\User',
                12 => 'App\\Entity\\Album',
                14 => 'App\\Entity\\ClassifiedAd',
            ],
        ],
    ],
    $o[0],
    []
); } },
4 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Album',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\AlbumRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'title' => $o[2],
                    'description' => $o[3],
                    'cover' => $o[4],
                    'createdAt' => $o[5],
                    'updatedAt' => $o[6],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'description' => 'description',
                    'cover' => 'cover',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'description' => 'description',
                    'cover' => 'cover',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'albums',
                ],
            ],
            'lifecycleCallbacks' => [
                [
                    'preUpdate' => [
                        'touch',
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'photos' => $o[7],
                ],
            ],
            'idGenerator' => [
                $o[8],
            ],
            'name' => [
                'App\\Entity\\Album',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'text',
                'string',
                'datetime_immutable',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'title',
                'description',
                'cover',
                'createdAt',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'title',
                'description',
                'cover',
                'created_at',
                'updated_at',
            ],
            'length' => [
                2 => 180,
                4 => 255,
            ],
            'nullable' => [
                3 => true,
                true,
            ],
            'cascade' => [
                7 => [
                    'persist',
                ],
            ],
            'fetch' => [
                7 => 2,
            ],
            'sourceEntity' => [
                7 => 'App\\Entity\\Album',
            ],
            'mappedBy' => [
                7 => 'album',
            ],
            'orderBy' => [
                7 => [
                    'uploadedAt' => 'DESC',
                ],
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                7 => 'photos',
            ],
            'targetEntity' => [
                7 => 'App\\Entity\\Photo',
            ],
        ],
    ],
    $o[0],
    []
); } },
5 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Article',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ArticleRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'title' => $o[2],
                    'slug' => $o[3],
                    'content' => $o[4],
                    'cover' => $o[5],
                    'isPublished' => $o[6],
                    'isMembersOnly' => $o[7],
                    'pinned' => $o[8],
                    'publishedAt' => $o[9],
                    'createdAt' => $o[10],
                    'updatedAt' => $o[11],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'slug' => 'slug',
                    'content' => 'content',
                    'cover' => 'cover',
                    'is_published' => 'isPublished',
                    'is_members_only' => 'isMembersOnly',
                    'pinned' => 'pinned',
                    'published_at' => 'publishedAt',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'slug' => 'slug',
                    'content' => 'content',
                    'cover' => 'cover',
                    'isPublished' => 'is_published',
                    'isMembersOnly' => 'is_members_only',
                    'pinned' => 'pinned',
                    'publishedAt' => 'published_at',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'article',
                ],
            ],
            'lifecycleCallbacks' => [
                [
                    'prePersist' => [
                        'onPrePersist',
                    ],
                    'preUpdate' => [
                        'onPreUpdate',
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'author' => $o[12],
                    'attachments' => $o[14],
                ],
            ],
            'idGenerator' => [
                $o[15],
            ],
            'name' => [
                'App\\Entity\\Article',
                13 => 'author_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'text',
                'string',
                'boolean',
                'boolean',
                'boolean',
                'datetime_immutable',
                'datetime_immutable',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'title',
                'slug',
                'content',
                'cover',
                'isPublished',
                'isMembersOnly',
                'pinned',
                'publishedAt',
                'createdAt',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'title',
                'slug',
                'content',
                'cover',
                'is_published',
                'is_members_only',
                'pinned',
                'published_at',
                'created_at',
                'updated_at',
            ],
            'length' => [
                2 => 255,
                255,
                5 => 255,
            ],
            'unique' => [
                3 => true,
                13 => false,
            ],
            'nullable' => [
                5 => true,
                9 => true,
                13 => false,
            ],
            'options' => [
                6 => [
                    'default' => false,
                ],
                [
                    'default' => false,
                ],
                [
                    'default' => false,
                ],
            ],
            'fetch' => [
                12 => 2,
                14 => 2,
            ],
            'sourceEntity' => [
                12 => 'App\\Entity\\Article',
                14 => 'App\\Entity\\Article',
            ],
            'inversedBy' => [
                12 => 'articles',
            ],
            'sourceToTargetKeyColumns' => [
                12 => [
                    'author_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                12 => [
                    'id' => 'author_id',
                ],
            ],
            'joinColumns' => [
                12 => [
                    $o[13],
                ],
            ],
            'joinColumnFieldNames' => [
                12 => [
                    'author_id' => 'author_id',
                ],
            ],
            'deferrable' => [
                13 => false,
            ],
            'referencedColumnName' => [
                13 => 'id',
            ],
            'cascade' => [
                14 => [
                    'persist',
                    'remove',
                ],
            ],
            'orphanRemoval' => [
                14 => true,
            ],
            'mappedBy' => [
                14 => 'article',
            ],
            'orderBy' => [
                14 => [
                    'position' => 'ASC',
                ],
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                12 => 'author',
                14 => 'attachments',
            ],
            'targetEntity' => [
                12 => 'App\\Entity\\User',
                14 => 'App\\Entity\\ArticleAttachment',
            ],
        ],
    ],
    $o[0],
    []
); } },
6 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\BoardMember',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\BoardMemberRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'surname' => $o[2],
                    'name' => $o[3],
                    'role' => $o[4],
                    'photoName' => $o[5],
                    'updatedAt' => $o[6],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'surname' => 'surname',
                    'name' => 'name',
                    'role' => 'role',
                    'photo_name' => 'photoName',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'surname' => 'surname',
                    'name' => 'name',
                    'role' => 'role',
                    'photoName' => 'photo_name',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'board_member',
                ],
            ],
            'idGenerator' => [
                $o[7],
            ],
            'name' => [
                'App\\Entity\\BoardMember',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'string',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'surname',
                'name',
                'role',
                'photoName',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'surname',
                'name',
                'role',
                'photo_name',
                'updated_at',
            ],
            'length' => [
                2 => 255,
                255,
                255,
                255,
            ],
            'nullable' => [
                5 => true,
                true,
            ],
        ],
    ],
    $o[0],
    []
); } },
7 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Membership',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\MembershipRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'year' => $o[2],
                    'status' => $o[3],
                    'paidAt' => $o[4],
                    'helloAssoRef' => $o[5],
                    'createdAt' => $o[6],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'year' => 'year',
                    'status' => 'status',
                    'paid_at' => 'paidAt',
                    'hello_asso_ref' => 'helloAssoRef',
                    'created_at' => 'createdAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'year' => 'year',
                    'status' => 'status',
                    'paidAt' => 'paid_at',
                    'helloAssoRef' => 'hello_asso_ref',
                    'createdAt' => 'created_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'memberships',
                    'uniqueConstraints' => [
                        'UNIQ_membership_user_year' => [
                            'columns' => [
                                'user_id',
                                'year',
                            ],
                        ],
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'user' => $o[7],
                ],
            ],
            'idGenerator' => [
                $o[9],
            ],
            'name' => [
                'App\\Entity\\Membership',
                8 => 'user_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'smallint',
                'string',
                'datetime_immutable',
                'string',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'year',
                'status',
                'paidAt',
                'helloAssoRef',
                'createdAt',
            ],
            'columnName' => [
                1 => 'id',
                'year',
                'status',
                'paid_at',
                'hello_asso_ref',
                'created_at',
            ],
            'enumType' => [
                3 => 'App\\Enum\\MembershipStatus',
            ],
            'nullable' => [
                4 => true,
                true,
                8 => false,
            ],
            'length' => [
                5 => 120,
            ],
            'fetch' => [
                7 => 2,
            ],
            'sourceEntity' => [
                7 => 'App\\Entity\\Membership',
            ],
            'inversedBy' => [
                7 => 'memberships',
            ],
            'sourceToTargetKeyColumns' => [
                7 => [
                    'user_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                7 => [
                    'id' => 'user_id',
                ],
            ],
            'joinColumns' => [
                7 => [
                    $o[8],
                ],
            ],
            'joinColumnFieldNames' => [
                7 => [
                    'user_id' => 'user_id',
                ],
            ],
            'deferrable' => [
                8 => false,
            ],
            'unique' => [
                8 => false,
            ],
            'referencedColumnName' => [
                8 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                7 => 'user',
            ],
            'targetEntity' => [
                7 => 'App\\Entity\\User',
            ],
        ],
    ],
    $o[0],
    []
); } },
8 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\MembershipApplication',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\MembershipApplicationRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'firstName' => $o[2],
                    'lastName' => $o[3],
                    'email' => $o[4],
                    'phone' => $o[5],
                    'message' => $o[6],
                    'status' => $o[7],
                    'targetYear' => $o[8],
                    'processingNote' => $o[9],
                    'processedAt' => $o[10],
                    'provider' => $o[11],
                    'providerPaymentId' => $o[12],
                    'amountCents' => $o[13],
                    'currency' => $o[14],
                    'rawPayload' => $o[15],
                    'receivedAt' => $o[16],
                    'createdAt' => $o[17],
                    'updatedAt' => $o[18],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'first_name' => 'firstName',
                    'last_name' => 'lastName',
                    'email' => 'email',
                    'phone' => 'phone',
                    'message' => 'message',
                    'status' => 'status',
                    'target_year' => 'targetYear',
                    'processing_note' => 'processingNote',
                    'processed_at' => 'processedAt',
                    'provider' => 'provider',
                    'provider_payment_id' => 'providerPaymentId',
                    'amount_cents' => 'amountCents',
                    'currency' => 'currency',
                    'raw_payload' => 'rawPayload',
                    'received_at' => 'receivedAt',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'firstName' => 'first_name',
                    'lastName' => 'last_name',
                    'email' => 'email',
                    'phone' => 'phone',
                    'message' => 'message',
                    'status' => 'status',
                    'targetYear' => 'target_year',
                    'processingNote' => 'processing_note',
                    'processedAt' => 'processed_at',
                    'provider' => 'provider',
                    'providerPaymentId' => 'provider_payment_id',
                    'amountCents' => 'amount_cents',
                    'currency' => 'currency',
                    'rawPayload' => 'raw_payload',
                    'receivedAt' => 'received_at',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'membership_applications',
                    'indexes' => [
                        'idx_email_year' => [
                            'columns' => [
                                'email',
                                'target_year',
                            ],
                        ],
                    ],
                    'uniqueConstraints' => [
                        'uniq_provider_payment' => [
                            'columns' => [
                                'provider',
                                'provider_payment_id',
                            ],
                        ],
                    ],
                ],
            ],
            'lifecycleCallbacks' => [
                [
                    'prePersist' => [
                        'onPrePersist',
                    ],
                    'preUpdate' => [
                        'touch',
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'processedBy' => $o[19],
                ],
            ],
            'idGenerator' => [
                $o[21],
            ],
            'name' => [
                'App\\Entity\\MembershipApplication',
                20 => 'processed_by_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'string',
                'text',
                'string',
                'smallint',
                'text',
                'datetime_immutable',
                'string',
                'string',
                'integer',
                'string',
                'json',
                'datetime_immutable',
                'datetime_immutable',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'firstName',
                'lastName',
                'email',
                'phone',
                'message',
                'status',
                'targetYear',
                'processingNote',
                'processedAt',
                'provider',
                'providerPaymentId',
                'amountCents',
                'currency',
                'rawPayload',
                'receivedAt',
                'createdAt',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'first_name',
                'last_name',
                'email',
                'phone',
                'message',
                'status',
                'target_year',
                'processing_note',
                'processed_at',
                'provider',
                'provider_payment_id',
                'amount_cents',
                'currency',
                'raw_payload',
                'received_at',
                'created_at',
                'updated_at',
            ],
            'length' => [
                2 => 100,
                100,
                180,
                30,
                11 => 30,
                100,
                14 => 3,
            ],
            'nullable' => [
                5 => true,
                true,
                9 => true,
                true,
                12 => true,
                true,
                15 => true,
                true,
                20 => true,
            ],
            'enumType' => [
                7 => 'App\\Enum\\ApplicationStatus',
            ],
            'options' => [
                11 => [
                    'default' => 'MANUAL',
                ],
                13 => [
                    'unsigned' => true,
                ],
                [
                    'default' => 'EUR',
                ],
            ],
            'fetch' => [
                19 => 2,
            ],
            'sourceEntity' => [
                19 => 'App\\Entity\\MembershipApplication',
            ],
            'inversedBy' => [
                19 => 'processedApplications',
            ],
            'sourceToTargetKeyColumns' => [
                19 => [
                    'processed_by_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                19 => [
                    'id' => 'processed_by_id',
                ],
            ],
            'joinColumns' => [
                19 => [
                    $o[20],
                ],
            ],
            'joinColumnFieldNames' => [
                19 => [
                    'processed_by_id' => 'processed_by_id',
                ],
            ],
            'referencedColumnName' => [
                20 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                19 => 'processedBy',
            ],
            'targetEntity' => [
                19 => 'App\\Entity\\User',
            ],
        ],
    ],
    $o[0],
    []
); } },
9 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\OutingRequest',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\OutingRequestRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'seats' => $o[2],
                    'contactName' => $o[3],
                    'email' => $o[4],
                    'phone' => $o[5],
                    'emergencyPhone' => $o[6],
                    'guestNames' => $o[7],
                    'message' => $o[8],
                    'status' => $o[9],
                    'createdAt' => $o[10],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'seats' => 'seats',
                    'contact_name' => 'contactName',
                    'email' => 'email',
                    'phone' => 'phone',
                    'emergency_phone' => 'emergencyPhone',
                    'guest_names' => 'guestNames',
                    'message' => 'message',
                    'status' => 'status',
                    'created_at' => 'createdAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'seats' => 'seats',
                    'contactName' => 'contact_name',
                    'email' => 'email',
                    'phone' => 'phone',
                    'emergencyPhone' => 'emergency_phone',
                    'guestNames' => 'guest_names',
                    'message' => 'message',
                    'status' => 'status',
                    'createdAt' => 'created_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'outing_request',
                ],
            ],
            'lifecycleCallbacks' => [
                [
                    'prePersist' => [
                        'onPrePersist',
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'user' => $o[11],
                    'event' => $o[13],
                ],
            ],
            'idGenerator' => [
                $o[15],
            ],
            'name' => [
                'App\\Entity\\OutingRequest',
                12 => 'user_id',
                14 => 'event_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'smallint',
                'string',
                'string',
                'string',
                'string',
                'text',
                'text',
                'string',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'seats',
                'contactName',
                'email',
                'phone',
                'emergencyPhone',
                'guestNames',
                'message',
                'status',
                'createdAt',
            ],
            'columnName' => [
                1 => 'id',
                'seats',
                'contact_name',
                'email',
                'phone',
                'emergency_phone',
                'guest_names',
                'message',
                'status',
                'created_at',
            ],
            'options' => [
                2 => [
                    'default' => 1,
                ],
            ],
            'length' => [
                3 => 255,
                255,
                50,
                50,
                9 => 16,
            ],
            'nullable' => [
                3 => true,
                true,
                true,
                true,
                true,
                true,
                12 => true,
                14 => false,
            ],
            'fetch' => [
                11 => 2,
                13 => 2,
            ],
            'sourceEntity' => [
                11 => 'App\\Entity\\OutingRequest',
                13 => 'App\\Entity\\OutingRequest',
            ],
            'inversedBy' => [
                11 => 'outingRequests',
                13 => 'outingRequests',
            ],
            'sourceToTargetKeyColumns' => [
                11 => [
                    'user_id' => 'id',
                ],
                13 => [
                    'event_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                11 => [
                    'id' => 'user_id',
                ],
                13 => [
                    'id' => 'event_id',
                ],
            ],
            'joinColumns' => [
                11 => [
                    $o[12],
                ],
                13 => [
                    $o[14],
                ],
            ],
            'joinColumnFieldNames' => [
                11 => [
                    'user_id' => 'user_id',
                ],
                13 => [
                    'event_id' => 'event_id',
                ],
            ],
            'deferrable' => [
                12 => false,
                14 => false,
            ],
            'unique' => [
                12 => false,
                14 => false,
            ],
            'onDelete' => [
                12 => 'SET NULL',
            ],
            'referencedColumnName' => [
                12 => 'id',
                14 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                11 => 'user',
                13 => 'event',
            ],
            'targetEntity' => [
                11 => 'App\\Entity\\User',
                13 => 'App\\Entity\\Event',
            ],
        ],
    ],
    $o[0],
    []
); } },
10 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Page',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\PageRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'title' => $o[2],
                    'slug' => $o[3],
                    'body' => $o[4],
                    'isPublished' => $o[5],
                    'isMembersOnly' => $o[6],
                    'metaTitle' => $o[7],
                    'metaDescription' => $o[8],
                    'createdAt' => $o[9],
                    'updatedAt' => $o[10],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'slug' => 'slug',
                    'body' => 'body',
                    'is_published' => 'isPublished',
                    'is_members_only' => 'isMembersOnly',
                    'meta_title' => 'metaTitle',
                    'meta_description' => 'metaDescription',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'slug' => 'slug',
                    'body' => 'body',
                    'isPublished' => 'is_published',
                    'isMembersOnly' => 'is_members_only',
                    'metaTitle' => 'meta_title',
                    'metaDescription' => 'meta_description',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'pages',
                    'uniqueConstraints' => [
                        'UNIQ_page_slug' => [
                            'columns' => [
                                'slug',
                            ],
                        ],
                    ],
                ],
            ],
            'lifecycleCallbacks' => [
                [
                    'preUpdate' => [
                        'touch',
                    ],
                ],
            ],
            'idGenerator' => [
                $o[11],
            ],
            'name' => [
                'App\\Entity\\Page',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'text',
                'boolean',
                'boolean',
                'string',
                'string',
                'datetime_immutable',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'title',
                'slug',
                'body',
                'isPublished',
                'isMembersOnly',
                'metaTitle',
                'metaDescription',
                'createdAt',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'title',
                'slug',
                'body',
                'is_published',
                'is_members_only',
                'meta_title',
                'meta_description',
                'created_at',
                'updated_at',
            ],
            'length' => [
                2 => 180,
                200,
                7 => 180,
                255,
            ],
            'options' => [
                5 => [
                    'default' => false,
                ],
                [
                    'default' => false,
                ],
            ],
            'nullable' => [
                7 => true,
                true,
            ],
        ],
    ],
    $o[0],
    []
); } },
11 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\PartnerLink',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\PartnerLinkRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'label' => $o[2],
                    'url' => $o[3],
                    'type' => $o[4],
                    'logo' => $o[5],
                    'position' => $o[6],
                    'isActive' => $o[7],
                    'createdAt' => $o[8],
                    'updatedAt' => $o[9],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'label' => 'label',
                    'url' => 'url',
                    'type' => 'type',
                    'logo' => 'logo',
                    'position' => 'position',
                    'is_active' => 'isActive',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'label' => 'label',
                    'url' => 'url',
                    'type' => 'type',
                    'logo' => 'logo',
                    'position' => 'position',
                    'isActive' => 'is_active',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'partner_links',
                    'uniqueConstraints' => [
                        'UNIQ_partner_link_url' => [
                            'columns' => [
                                'url',
                            ],
                        ],
                    ],
                ],
            ],
            'lifecycleCallbacks' => [
                [
                    'preUpdate' => [
                        'touch',
                    ],
                ],
            ],
            'idGenerator' => [
                $o[10],
            ],
            'name' => [
                'App\\Entity\\PartnerLink',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'string',
                'smallint',
                'boolean',
                'datetime_immutable',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'label',
                'url',
                'type',
                'logo',
                'position',
                'isActive',
                'createdAt',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'label',
                'url',
                'type',
                'logo',
                'position',
                'is_active',
                'created_at',
                'updated_at',
            ],
            'length' => [
                2 => 160,
                255,
                60,
                255,
            ],
            'nullable' => [
                4 => true,
                true,
            ],
            'options' => [
                6 => [
                    'default' => 0,
                ],
                [
                    'default' => true,
                ],
            ],
        ],
    ],
    $o[0],
    []
); } },
12 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\User',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\UserRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'email' => $o[2],
                    'roles' => $o[3],
                    'password' => $o[4],
                    'firstName' => $o[5],
                    'lastName' => $o[6],
                    'phone' => $o[7],
                    'avatar' => $o[8],
                    'newsletterOptIn' => $o[9],
                    'createdAt' => $o[10],
                    'updatedAt' => $o[11],
                    'isApproved' => $o[12],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'email' => 'email',
                    'roles' => 'roles',
                    'password' => 'password',
                    'first_name' => 'firstName',
                    'last_name' => 'lastName',
                    'phone' => 'phone',
                    'avatar' => 'avatar',
                    'newsletter_opt_in' => 'newsletterOptIn',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                    'is_approved' => 'isApproved',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'email' => 'email',
                    'roles' => 'roles',
                    'password' => 'password',
                    'firstName' => 'first_name',
                    'lastName' => 'last_name',
                    'phone' => 'phone',
                    'avatar' => 'avatar',
                    'newsletterOptIn' => 'newsletter_opt_in',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                    'isApproved' => 'is_approved',
                ],
            ],
            'table' => [
                [
                    'name' => 'user',
                    'quoted' => true,
                ],
            ],
            'lifecycleCallbacks' => [
                [
                    'prePersist' => [
                        'onPrePersist',
                    ],
                    'preUpdate' => [
                        'onPreUpdate',
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'articles' => $o[13],
                    'eventsCreated' => $o[14],
                    'classifiedAds' => $o[15],
                    'photos' => $o[16],
                    'outingRequests' => $o[17],
                    'processedApplications' => $o[18],
                    'memberships' => $o[19],
                ],
            ],
            'idGenerator' => [
                $o[20],
            ],
            'name' => [
                'App\\Entity\\User',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'json',
                'string',
                'string',
                'string',
                'string',
                'string',
                'boolean',
                'datetime_immutable',
                'datetime_immutable',
                'boolean',
            ],
            'fieldName' => [
                1 => 'id',
                'email',
                'roles',
                'password',
                'firstName',
                'lastName',
                'phone',
                'avatar',
                'newsletterOptIn',
                'createdAt',
                'updatedAt',
                'isApproved',
            ],
            'columnName' => [
                1 => 'id',
                'email',
                'roles',
                'password',
                'first_name',
                'last_name',
                'phone',
                'avatar',
                'newsletter_opt_in',
                'created_at',
                'updated_at',
                'is_approved',
            ],
            'length' => [
                2 => 180,
                5 => 255,
                255,
                50,
                255,
            ],
            'unique' => [
                2 => true,
            ],
            'nullable' => [
                7 => true,
                true,
            ],
            'options' => [
                9 => [
                    'default' => false,
                ],
            ],
            'fetch' => [
                13 => 2,
                2,
                2,
                2,
                2,
                2,
                2,
            ],
            'sourceEntity' => [
                13 => 'App\\Entity\\User',
                'App\\Entity\\User',
                'App\\Entity\\User',
                'App\\Entity\\User',
                'App\\Entity\\User',
                'App\\Entity\\User',
                'App\\Entity\\User',
            ],
            'mappedBy' => [
                13 => 'author',
                'createdBy',
                'owner',
                'owner',
                'user',
                'processedBy',
                'user',
            ],
            'cascade' => [
                19 => [
                    'persist',
                ],
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                13 => 'articles',
                'eventsCreated',
                'classifiedAds',
                'photos',
                'outingRequests',
                'processedApplications',
                'memberships',
            ],
            'targetEntity' => [
                13 => 'App\\Entity\\Article',
                'App\\Entity\\Event',
                'App\\Entity\\ClassifiedAd',
                'App\\Entity\\Photo',
                'App\\Entity\\OutingRequest',
                'App\\Entity\\MembershipApplication',
                'App\\Entity\\Membership',
            ],
        ],
    ],
    $o[0],
    []
); } },
13 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'Vich\\UploaderBundle\\Entity',
            ],
            'rootEntityName' => [
                'Vich\\UploaderBundle\\Entity\\File',
            ],
            'isEmbeddedClass' => [
                true,
            ],
            'fieldMappings' => [
                [
                    'name' => $o[1],
                    'originalName' => $o[2],
                    'mimeType' => $o[3],
                    'size' => $o[4],
                    'dimensions' => $o[5],
                ],
            ],
            'fieldNames' => [
                [
                    'name' => 'name',
                    'original_name' => 'originalName',
                    'mime_type' => 'mimeType',
                    'size' => 'size',
                    'dimensions' => 'dimensions',
                ],
            ],
            'columnNames' => [
                [
                    'name' => 'name',
                    'originalName' => 'original_name',
                    'mimeType' => 'mime_type',
                    'size' => 'size',
                    'dimensions' => 'dimensions',
                ],
            ],
            'table' => [
                [
                    'name' => 'file',
                ],
            ],
            'idGenerator' => [
                $o[6],
            ],
            'name' => [
                'Vich\\UploaderBundle\\Entity\\File',
            ],
            'nullable' => [
                1 => true,
                true,
                true,
                true,
                true,
            ],
            'type' => [
                1 => 'string',
                'string',
                'string',
                'integer',
                'simple_array',
            ],
            'fieldName' => [
                1 => 'name',
                'originalName',
                'mimeType',
                'size',
                'dimensions',
            ],
            'columnName' => [
                1 => 'name',
                'original_name',
                'mime_type',
                'size',
                'dimensions',
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
