# config/services.yaml
parameters:
    recaptcha_site: '%env(RECAPTCHA_SITE_KEY)%'
    recaptcha_secret: '%env(RECAPTCHA_SECRET_KEY)%'

    # Arzal coordinates
    app.weather_lat: 47.52
    app.weather_lon: -2.30
    app.tide_lat: 47.45
    app.tide_lon: -2.50

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Make classes in src/ available to be used as services
    # This creates a service per class whose id is the FQCN
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Controllers as services
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # App\Controller\HeaderController:
    #   bind:
    #     $weatherLat: '%app.weather_lat%'
    #     $weatherLon: '%app.weather_lon%'
    #     $tideLat: '%app.tide_lat%'
    #     $tideLon: '%app.tide_lon%'
