<?php

namespace ContainerDmfHG8n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccountAdControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YeOxpsH.App\Controller\Account\AccountAdController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YeOxpsH.App\\Controller\\Account\\AccountAdController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\ClassifiedAdRepository', 'getClassifiedAdRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\ClassifiedAdRepository',
        ]))->withContext('App\\Controller\\Account\\AccountAdController::index()', $container);
    }
}
