<?php

namespace ContainerDmfHG8n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArchiveImageControllerinfoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b2vch_B.App\Controller\Admin\ArchiveImageController::info()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b2vch_B.App\\Controller\\Admin\\ArchiveImageController::info()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'image' => ['privates', '.errored..service_locator.b2vch_B.App\\Entity\\ArchiveImage', NULL, 'Cannot autowire service ".service_locator.b2vch_B": it needs an instance of "App\\Entity\\ArchiveImage" but this type has been excluded in "config/services.yaml".'],
        ], [
            'image' => 'App\\Entity\\ArchiveImage',
        ]))->withContext('App\\Controller\\Admin\\ArchiveImageController::info()', $container);
    }
}
