<?php

namespace ContainerDmfHG8n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttachmentControllerdownloadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VYwb7sT.App\Controller\AttachmentController::download()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VYwb7sT.App\\Controller\\AttachmentController::download()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'attachment' => ['privates', '.errored..service_locator.VYwb7sT.App\\Entity\\ArticleAttachment', NULL, 'Cannot autowire service ".service_locator.VYwb7sT": it needs an instance of "App\\Entity\\ArticleAttachment" but this type has been excluded in "config/services.yaml".'],
        ], [
            'attachment' => 'App\\Entity\\ArticleAttachment',
        ]))->withContext('App\\Controller\\AttachmentController::download()', $container);
    }
}
