<?php

namespace ContainerDmfHG8n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassifiedAdControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Tfsgm_V.App\Controller\ClassifiedAdController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Tfsgm_V.App\\Controller\\ClassifiedAdController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ad' => ['privates', '.errored..service_locator.Tfsgm_V.App\\Entity\\ClassifiedAd', NULL, 'Cannot autowire service ".service_locator.Tfsgm_V": it needs an instance of "App\\Entity\\ClassifiedAd" but this type has been excluded in "config/services.yaml".'],
        ], [
            'ad' => 'App\\Entity\\ClassifiedAd',
        ]))->withContext('App\\Controller\\ClassifiedAdController::show()', $container);
    }
}
