<?php

namespace ContainerDmfHG8n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassifiedAdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9S0t5iQ.App\Entity\ClassifiedAd' shared service.
     *
     * @return \App\Entity\ClassifiedAd
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9S0t5iQ": it needs an instance of "App\\Entity\\ClassifiedAd" but this type has been excluded in "config/services.yaml".');
    }
}
