<?php

namespace ContainerDmfHG8n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassifiedAdControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JvaWyXb.App\Controller\ClassifiedAdController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JvaWyXb.App\\Controller\\ClassifiedAdController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'service' => ['privates', 'App\\Service\\ClassifiedAdService', 'getClassifiedAdServiceService', true],
        ], [
            'service' => 'App\\Service\\ClassifiedAdService',
        ]))->withContext('App\\Controller\\ClassifiedAdController::index()', $container);
    }
}
