<?php

namespace ContainerDmfHG8n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventRegistrationControllerregisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C7K2DhT.App\Controller\EventRegistrationController::register()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C7K2DhT.App\\Controller\\EventRegistrationController::register()'] = ($container->privates['.service_locator.C7K2DhT'] ?? $container->load('get_ServiceLocator_C7K2DhTService'))->withContext('App\\Controller\\EventRegistrationController::register()', $container);
    }
}
