<?php

namespace ContainerDmfHG8n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4ZMKHSv.App\Controller\HomeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4ZMKHSv.App\\Controller\\HomeController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articles' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
            'classifieds' => ['privates', 'App\\Service\\ClassifiedAdService', 'getClassifiedAdServiceService', true],
            'partnerLinks' => ['privates', 'App\\Repository\\PartnerLinkRepository', 'getPartnerLinkRepositoryService', true],
        ], [
            'articles' => 'App\\Repository\\ArticleRepository',
            'eventRepository' => 'App\\Repository\\EventRepository',
            'classifieds' => 'App\\Service\\ClassifiedAdService',
            'partnerLinks' => 'App\\Repository\\PartnerLinkRepository',
        ]))->withContext('App\\Controller\\HomeController::index()', $container);
    }
}
