<?php

namespace ContainerDmfHG8n;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhotoThumbnailSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\PhotoThumbnailSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\PhotoThumbnailSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'PhotoThumbnailSubscriber.php';

        $a = ($container->services['liip_imagine.cache.manager'] ?? self::getLiipImagine_Cache_ManagerService($container));

        if (isset($container->privates['App\\EventSubscriber\\PhotoThumbnailSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\PhotoThumbnailSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\PhotoThumbnailSubscriber'] = new \App\EventSubscriber\PhotoThumbnailSubscriber($a);
    }
}
