<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRzmuz2U\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRzmuz2U/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerRzmuz2U.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerRzmuz2U\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerRzmuz2U\App_KernelDevContainer([
    'container.build_hash' => 'Rzmuz2U',
    'container.build_id' => 'fbfda259',
    'container.build_time' => 1768499734,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRzmuz2U');
