<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDmfHG8n\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDmfHG8n/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDmfHG8n.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDmfHG8n\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDmfHG8n\App_KernelDevDebugContainer([
    'container.build_hash' => 'DmfHG8n',
    'container.build_id' => '0ebf8c70',
    'container.build_time' => 1768502330,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDmfHG8n');
