<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Page extends \App\Entity\Page implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'body' => [parent::class, 'body', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isMembersOnly' => [parent::class, 'isMembersOnly', null, 16],
        "\0".parent::class."\0".'isPublished' => [parent::class, 'isPublished', null, 16],
        "\0".parent::class."\0".'metaDescription' => [parent::class, 'metaDescription', null, 16],
        "\0".parent::class."\0".'metaTitle' => [parent::class, 'metaTitle', null, 16],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null, 16],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'body' => [parent::class, 'body', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isMembersOnly' => [parent::class, 'isMembersOnly', null, 16],
        'isPublished' => [parent::class, 'isPublished', null, 16],
        'metaDescription' => [parent::class, 'metaDescription', null, 16],
        'metaTitle' => [parent::class, 'metaTitle', null, 16],
        'slug' => [parent::class, 'slug', null, 16],
        'title' => [parent::class, 'title', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
