<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MembershipApplication extends \App\Entity\MembershipApplication implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'amountCents' => [parent::class, 'amountCents', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'currency' => [parent::class, 'currency', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'firstName' => [parent::class, 'firstName', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null, 16],
        "\0".parent::class."\0".'message' => [parent::class, 'message', null, 16],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null, 16],
        "\0".parent::class."\0".'processedAt' => [parent::class, 'processedAt', null, 16],
        "\0".parent::class."\0".'processedBy' => [parent::class, 'processedBy', null, 16],
        "\0".parent::class."\0".'processingNote' => [parent::class, 'processingNote', null, 16],
        "\0".parent::class."\0".'provider' => [parent::class, 'provider', null, 16],
        "\0".parent::class."\0".'providerPaymentId' => [parent::class, 'providerPaymentId', null, 16],
        "\0".parent::class."\0".'rawPayload' => [parent::class, 'rawPayload', null, 16],
        "\0".parent::class."\0".'receivedAt' => [parent::class, 'receivedAt', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'targetYear' => [parent::class, 'targetYear', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'amountCents' => [parent::class, 'amountCents', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'currency' => [parent::class, 'currency', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'firstName' => [parent::class, 'firstName', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'lastName' => [parent::class, 'lastName', null, 16],
        'message' => [parent::class, 'message', null, 16],
        'phone' => [parent::class, 'phone', null, 16],
        'processedAt' => [parent::class, 'processedAt', null, 16],
        'processedBy' => [parent::class, 'processedBy', null, 16],
        'processingNote' => [parent::class, 'processingNote', null, 16],
        'provider' => [parent::class, 'provider', null, 16],
        'providerPaymentId' => [parent::class, 'providerPaymentId', null, 16],
        'rawPayload' => [parent::class, 'rawPayload', null, 16],
        'receivedAt' => [parent::class, 'receivedAt', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'targetYear' => [parent::class, 'targetYear', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
