<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OutingRequest extends \App\Entity\OutingRequest implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'contactName' => [parent::class, 'contactName', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'emergencyPhone' => [parent::class, 'emergencyPhone', null, 16],
        "\0".parent::class."\0".'event' => [parent::class, 'event', null, 16],
        "\0".parent::class."\0".'guestNames' => [parent::class, 'guestNames', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'message' => [parent::class, 'message', null, 16],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null, 16],
        "\0".parent::class."\0".'seats' => [parent::class, 'seats', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'contactName' => [parent::class, 'contactName', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'emergencyPhone' => [parent::class, 'emergencyPhone', null, 16],
        'event' => [parent::class, 'event', null, 16],
        'guestNames' => [parent::class, 'guestNames', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'message' => [parent::class, 'message', null, 16],
        'phone' => [parent::class, 'phone', null, 16],
        'seats' => [parent::class, 'seats', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
