<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ArticleAttachment extends \App\Entity\ArticleAttachment implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'article' => [parent::class, 'article', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'file' => [parent::class, 'file', null, 16],
        "\0".parent::class."\0".'fileName' => [parent::class, 'fileName', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'mimeType' => [parent::class, 'mimeType', null, 16],
        "\0".parent::class."\0".'originalName' => [parent::class, 'originalName', null, 16],
        "\0".parent::class."\0".'position' => [parent::class, 'position', null, 16],
        "\0".parent::class."\0".'size' => [parent::class, 'size', null, 16],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'article' => [parent::class, 'article', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'file' => [parent::class, 'file', null, 16],
        'fileName' => [parent::class, 'fileName', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'mimeType' => [parent::class, 'mimeType', null, 16],
        'originalName' => [parent::class, 'originalName', null, 16],
        'position' => [parent::class, 'position', null, 16],
        'size' => [parent::class, 'size', null, 16],
        'title' => [parent::class, 'title', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
