<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Event extends \App\Entity\Event implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'createdBy' => [parent::class, 'createdBy', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'endAt' => [parent::class, 'endAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isMembersOnly' => [parent::class, 'isMembersOnly', null, 16],
        "\0".parent::class."\0".'lat' => [parent::class, 'lat', null, 16],
        "\0".parent::class."\0".'lng' => [parent::class, 'lng', null, 16],
        "\0".parent::class."\0".'locationName' => [parent::class, 'locationName', null, 16],
        "\0".parent::class."\0".'maxParticipants' => [parent::class, 'maxParticipants', null, 16],
        "\0".parent::class."\0".'outingRequests' => [parent::class, 'outingRequests', null, 16],
        "\0".parent::class."\0".'registrationOpen' => [parent::class, 'registrationOpen', null, 16],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null, 16],
        "\0".parent::class."\0".'startAt' => [parent::class, 'startAt', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'createdBy' => [parent::class, 'createdBy', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'endAt' => [parent::class, 'endAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isMembersOnly' => [parent::class, 'isMembersOnly', null, 16],
        'lat' => [parent::class, 'lat', null, 16],
        'lng' => [parent::class, 'lng', null, 16],
        'locationName' => [parent::class, 'locationName', null, 16],
        'maxParticipants' => [parent::class, 'maxParticipants', null, 16],
        'outingRequests' => [parent::class, 'outingRequests', null, 16],
        'registrationOpen' => [parent::class, 'registrationOpen', null, 16],
        'slug' => [parent::class, 'slug', null, 16],
        'startAt' => [parent::class, 'startAt', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'title' => [parent::class, 'title', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
